name: Build

on:
  push:
    branches: ["main"]
  pull_request:
  schedule:
    - cron: "0 0 * * *"

defaults:
  run:
    shell: bash -eux {0}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '3.8', '3.9', '3.10', "3.11" ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: Install dependencies
      run: python -m pip install -U jupyter_server

    - name: Build the extension
      run: |
        python -m pip install .
        jupyter server extension list 2>&1 | grep -ie "jprofiler.*OK"

        pip install build
        python -m build --sdist
        cp dist/*.tar.gz my_server_extension.tar.gz
        pip uninstall -y "jprofiler" jupyter_server
        rm -rf "jprofiler"

    - uses: actions/upload-artifact@v4
      with:
        name: my_server_extension-sdist-${{ matrix.os }}-py${{ matrix.python-version }}
        path: my_server_extension.tar.gz
        compression-level: 0

  test_sdist:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '3.8', '3.9', '3.10', "3.11" ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - uses: actions/download-artifact@v4
      with:
        name: my_server_extension-sdist-${{ matrix.os }}-py${{ matrix.python-version }}
        path: dist
    - name: Install and Test
      run: |
        pip install dist/my_server_extension.tar.gz
        pip install jupyter_server
        jupyter server extension list 2>&1 | grep -ie "jprofiler.*OK"

  combine_artifacts:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: my_server_extension-sdist-*
        merge-multiple: true
        path: combined_artifacts
    - uses: actions/upload-artifact@v4
      with:
        name: all_sdists
        path: combined_artifacts
        compression-level: 0
